name: Asana Integration
on:   
  push:
    branches:
      - main
      
      
jobs:
  asana_integration:
  runs-on: windows-latest
  
  steps:
    - name: Set up Git
      uses: actions/checkout@v2
      
    - name: Set up Asana
    
      
