name: Asana Integration

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - name: Install Asana CLI
        run: npm install -g asana

      - name: Set up Asana GitHub integration
        run: asana github setup --token <YOUR_PERSONAL_ACCESS_TOKEN>

      - name: Create Asana task
        run: asana create-task --name "New Pull Request: ${{ github.event.pull_request.title }}" --project <ASANA_PROJECT_ID>
