
name: Asana Integration

on:
  push:
    branches:
      - main

jobs:
  asana:
    runs-on: windows-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create Asana task
        run: |
          npm install --save axios
          node -e "
            const axios = require('axios');
            const taskName = 'New Push:';
            const branchName = process.env.GITHUB_REF.split('/').pop();
            const commitAuthor = process.env.GITHUB_ACTOR;
            const commitMessage = process.env.GITHUB_SHA;
            const projectId = '1204763105220463'; // Replace with your Asana project ID
            const token = '1/1204760161937729:b3bcc2c3e471c304b84924c4d1290a59'; // Replace with your Asana Personal Access Token

            const createTask = async () => {
              try {
                const response = await axios.post(
                  'https://app.asana.com/api/1.0/tasks',
                  {
                    data: {
                      name: taskName,
                      notes: 'Branch: ' + branchName + '\\nAuthor: ' + commitAuthor + '\\nCommit SHA: ' + commitMessage,
                      projects: [projectId],
                    },
                  },
                  {
                    headers: {
                      'Authorization': 'Bearer ' + token,
                    },
                  }
                );
                console.log('Asana task created with ID:', response.data.data.id);
              } catch (error) {
                console.error('Error creating Asana task:', error.response.data.errors);
              }
            };

            createTask();
          "

