

          
name: Asana Integration

on:
  push:
    branches:
      - main

jobs:
  asana_integration:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create Asana Task
        env:
          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
          ASANA_PROJECT_ID: "1/1204760161937729:2ef4a223f8255b7789d484bed4b175fd"
        run: |
          Invoke-WebRequest -Uri "https://app.asana.com/api/1.0/tasks" `
          -Headers @{
            "Authorization" = "Bearer $ASANA_ACCESS_TOKEN"
            "Content-Type" = "application/json"
          } `
          -Method POST `
          -Body '{ "data": { "name": "New task from GitHub", "projects": ["<ASANA_PROJECT_ID>"] } }'

