name: Asana Integration

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - name: Install Asana CLI
        run: npm install -g asana

      - name: Set up Asana GitHub integration
        run: asana github setup --token 1/1204760161937729:b3bcc2c3e471c304b84924c4d1290a59

      - name: Create Asana task
        run: asana create-task --name "New Pull Request: ${{ github.event.pull_request.title }}" --project 1204763105220463
