name: Asana Integration

on:
  push:
    branches:
      - main

jobs:
  asana_integration:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create Asana Task
        env:
          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
          ASANA_PROJECT_ID: "<ASANA_PROJECT_ID>"
        run: |
          curl -X POST -H "Authorization: Bearer $ASANA_ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"data\":{\"name\":\"New task from GitHub\",\"projects\":[\"$ASANA_PROJECT_ID\"]}}" \
          https://app.asana.com/api/1.0/tasks
