name: Asana Integration

on:
  push:
    branches:
      - main

jobs:
  asana_integration_job:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Asana CLI
        run: npm install -g asana-cli
      
      - name: Create Asana Task
        run: |
          asana configure --token ${{ secrets.ASANA_TOKEN }}
          asana create-task --workspace=my_workspace_id --project=my_project_id --name="New Task from GitHub"
