name: Asana Integration

on:
  push:
    branches:
      - main

jobs:
  asana_integration_job:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Asana CLI
        run: npm install -g asana-cli
      
      - name: Configure Asana CLI
        run: asana configure --api-key ${{ secrets.ASANA_API_KEY }}
      
      - name: Create Asana Task
        run: asana create-task --workspace=1204760162033794 --project=1204760620077158 --name="New Task from GitHub"
