name: Asana Integration

on:
  push:
    branches:
      - main

jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Asana CLI
        run: npm install -g asana

      - name: Set up Asana GitHub integration
        run: asana github setup --token ${{ secrets.GITHUB_TOKEN }}

      - name: Create Asana task
        run: |
          asana create-task --name "New Push: ${{ github.event.head_commit.message }}" \
          --project 1204763105220463


